# Azure Pipelines for Valhalla
#
# TODO: Shallow clone blocked by
#       https://developercommunity.visualstudio.com/content/problem/294872/yaml-build-ignores-fetchdepth.html
# TODO: Once CMake 3.13 is available replace -H with -S option
#
jobs:
  - job: VS2019
    displayName: 'Windows 2019 | VS2019'

    pool:
      vmImage: 'windows-2019'

    strategy:
      matrix:
        x86:
          PLATFORM: 'Win32'
          TRIPLET: 'x86'
        x64:
          PLATFORM: 'x64'
          TRIPLET: 'x64'

    variables:
      BUILD_CFG: 'Release'
      BUILD_DIR: '$(Agent.WorkFolder)\build'
      VCPKG_DIR: '$(Agent.WorkFolder)\vcpkg'
      VCPKG_REF: 'f4bd6423'

    steps:
      - script: git submodule update --init --recursive
        displayName: 'Pull submodules'

      
      - task: Cache@2
        displayName: 'Cache vcpkg's artifacts'
        inputs:
          key: .\.vcpkg_deps.txt | "$(VCPKG_REF)" | "$(Agent.OS)"
          path: "$(VCPKG_DIR)"

      - task: run-vcpkg@0
        displayName: 'Run vcpkg'
        inputs:
          vcpkgArguments: @$(Build.SourcesDirectory)/vcpkg_deps.txt
          vcpkgTriplet: "$(TRIPLET)-windows"
          vcpkgGitCommitId: $(VCPKG_REF)

      - script: |
          move /Y third_party\OSM-binary\src\fileformat.proto third_party\OSM-binary\src\fileformat.proto.orig
          move /Y third_party\OSM-binary\src\osmformat.proto third_party\OSM-binary\src\osmformat.proto.orig
          echo syntax = "proto2"; > third_party\OSM-binary\src\fileformat.proto
          type third_party\OSM-binary\src\fileformat.proto.orig >> third_party\OSM-binary\src\fileformat.proto
          echo syntax = "proto2"; > third_party\OSM-binary\src\osmformat.proto
          type third_party\OSM-binary\src\osmformat.proto.orig >> third_party\OSM-binary\src\osmformat.proto
          del /Q third_party\OSM-binary\src\fileformat.proto.orig
          del /Q third_party\OSM-binary\src\osmformat.proto.orig
        displayName: 'Patch .proto files of OSMPBF with syntax=proto2'

      - script: |
          cmake --version
          cmake -H$(Build.SourcesDirectory) -B%BUILD_DIR% -G "Visual Studio 16 2019" -A %PLATFORM% -T host=%TRIPLET% -DCMAKE_TOOLCHAIN_FILE=%VCPKG_DIR%\scripts\buildsystems\vcpkg.cmake -DVCPKG_APPLOCAL_DEPS=ON -DENABLE_CCACHE=OFF -DENABLE_DATA_TOOLS=ON -DENABLE_HTTP=OFF -DENABLE_PYTHON_BINDINGS=OFF -DENABLE_SERVICES=OFF -DENABLE_TOOLS=ON -DENABLE_BENCHMARKS=OFF -DLUA_INCLUDE_DIR=%VCPKG_DIR%\installed\%TRIPLET%-windows\include\luajit -DLUA_LIBRARIES=%VCPKG_DIR%\installed\%TRIPLET%-windows\lib\lua51.lib
        displayName: 'Run CMake to configure build'

      - script: |
          cmake --build %BUILD_DIR% --config %BUILD_CFG%
        displayName: 'Run CMake to build'

      - script: |
          %BUILD_DIR%\%BUILD_CFG%\valhalla_build_tiles.exe -c .\test\win\valhalla.json .\test\data\utrecht_netherlands.osm.pbf
          %BUILD_DIR%\%BUILD_CFG%\valhalla_run_route.exe --config .\test\win\valhalla.json -j "{\"locations\": [{\"lat\": 52.10205, \"lon\": 5.114651}, {\"lat\": 52.093113, \"lon\": 5.100918}], \"costing\": \"auto\"}"
          %BUILD_DIR%\%BUILD_CFG%\\valhalla_run_isochrone.exe --config .\test\win\valhalla.json -j "{\"locations\": [{\"lat\": 52.10205, \"lon\": 5.114651}], \"costing\": \"auto\", \"contours\":[{\"time\":15,\"color\":\"ff0000\"}]}"
        displayName: 'Test some executables'