name: Valhalla MinGW Build
on: [push]

jobs:
  build:
    name: MinGW64 build
    runs-on: ubuntu-latest
    container: fedora:rawhide
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Get dependencies
        run: |
          dnf install -y \
            cmake \
            gcc-c++ \
            git \
            make \
            mingw64-curl \
            mingw64-boost \
            mingw64-protobuf \
            mingw64-sqlite \
            mingw64-libspatialite \
            mingw64-geos \
            mingw64-python3 \
            protobuf-compiler
      - name: Configure and run build
        run: |
          mkdir build && cd build && \
          mingw64-cmake .. \
            -DCMAKE_CROSS_COMPILING=1 \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_TOOLS=ON \
            -DENABLE_DATA_TOOLS=OFF \
            -DENABLE_SERVICES=OFF \
            -DENABLE_PYTHON_BINDINGS=OFF \
            -DENABLE_CCACHE=OFF \
            -DENABLE_TESTS=OFF \
            -DENABLE_BENCHMARKS=OFF \
            -DLOGGING_LEVEL=DEBUG \
            -DBoost_PROGRAM_OPTIONS_LIBRARY=/usr/x86_64-w64-mingw32/sys-root/mingw/lib/libboost_program_options-mt-x64.dll.a && \
          mingw64-make -C$PWD -j2 VERBOSE=1
